exclude:
  - node_modules
  - script
sass:
  style: :compressed
remote_theme: pages-themes/primer@v0.6.0
title: Kosuke Kurihara, Ph.D. （栗原 康佑）
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
description:
google_analytics: G-W5WWQK7FXG
